name = "Crowpack Baseline"
author = "crow-maki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a9dc8c1805be04863c35e1f90d2633e9de5240c87bf8b397eec921a03ab41cf"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
