name = "Crowpack Baseline"
author = "crow-maki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8df73c4610f54bedf14adc9717b0851c34bbc9eaaf3f266e8050679dc9e9cffc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
