name = "Crowpack Baseline"
author = "crow-maki"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11bc33a012b66a0d7a11673e2db4d0da27a8c4816a5b2276fea5d7836850f36b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
